name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-14, ubuntu-24.04-arm, macos-13]
        build_type: [Release]
        staticcompile: [ON, OFF]

    steps:
    - name: Install dependencies for Linux
      if: contains(matrix.os, 'ubuntu')
      run: sudo apt-get update && sudo apt-get install -yq help2man libgmp-dev

    - name: Install gmp for Mac
      if: contains(matrix.os, 'macos')
      run: |
        wget https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz
        tar xf gmp-6.3.0.tar.xz
        cd gmp-6.3.0
        ./configure --enable-static -enable-cxx --enable-shared
        make -j8
        sudo make install
        cd ..

    - name: Install zlib for Mac dynamic
      if: contains(matrix.os, 'macos') && matrix.staticcompile == 'OFF'
      run: |
        wget https://www.zlib.net/zlib-1.3.1.tar.gz
        tar xzvf zlib-1.3.1.tar.gz
        cd zlib-1.3.1
        ./configure
        make -j8
        sudo make install
        cd ..

    - name: Install zlib for Mac static
      if: contains(matrix.os, 'macos') && matrix.staticcompile == 'ON'
      run: |
        wget https://www.zlib.net/zlib-1.3.1.tar.gz
        tar xzvf zlib-1.3.1.tar.gz
        cd zlib-1.3.1
        ./configure --static
        make -j8
        sudo make install
        cd ..

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: project
        submodules: 'true'
    - name: Configure & build
      run: |
        cd project
        mkdir -p build && cd build
        cmake \
        -DENABLE_TESTING=OFF \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DSTATICCOMPILE=${{ matrix.staticcompile }} \
        -S ..
        cmake --build . --config ${{matrix.build_type}} -v

    - name: Test
      run: ctest -C ${{matrix.build_type}} --verbose

    - name: Upload Artifact - Linux
      if: contains(matrix.os, 'ubuntu') && matrix.staticcompile == 'ON' && !contains(matrix.os, 'arm')
      uses: actions/upload-artifact@v4
      with:
        name: cryptominisat5-linux-amd64
        path: |
          project/build/cryptominisat5
          project/build/lib/*

    - name: Upload Artifact - Linux arm
      if: contains(matrix.os, 'ubuntu') && matrix.staticcompile == 'ON' && contains(matrix.os, 'arm')
      uses: actions/upload-artifact@v4
      with:
        name: cryptominisat-linux-arm64
        path: |
          project/build/cryptominisat5
          project/build/lib/*

    - name: Upload Artifact - Mac ARM64
      if: matrix.os == 'macos-14' && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: cryptominisat5-mac-arm64
        path: |
          project/build/cryptominisat5
          project/build/lib/*

    - name: Upload Artifact - Mac x86_64
      if: matrix.os == 'macos-13' && matrix.staticcompile == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: cryptominisat5-mac-x86_64
        path: |
          project/build/cryptominisat5
          project/build/lib/*
